---
title: "Figures"
author: "Patrice Pottier"
date: "latest update: `r format(Sys.time(), '%d %B %Y')`"
output: rmdformats::readthedown
editor_options: 
  chunk_output_type: console
---


```{r setup, include = FALSE}
# knitr setting
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE, 
  tidy = TRUE,
  cache = TRUE
)
```

# **Load packages and data**

## *Load packages*

```{r}
pacman::p_load(tidyverse,
               maps,
               ape,
               patchwork,
               ggtree, # devtools::install_github("YuLab-SMU/ggtree")
               ggtreeExtra, # devtools::install_github("xiangpin/ggtreeExtra")
               ggnewscale, # devtools::install_github("eliocamp/ggnewscale@v0.4.3")
               here,
               ggspatial,
               viridis,
               RColorBrewer,
               rnaturalearth,
               rnaturalearthdata,
               rnaturalearthhires,
               patchwork) 
```


## *Load data and tree*

```{r}
AmphiTherm <- read_csv("data/Cleaned_data_Amphitherm.csv") # Import data

tree <- read.tree("data/Consensus_tree_Jetz_Pyron_2018.tre") # Import tree
```


# **Figure 2** 

```{r, fig.height=10, fig.width=18}
world <- ne_countries(scale = "large", returnclass = "sf")
world <- world %>%
    filter(!grepl("Antarctica", name))

AmphiTherm_map <- AmphiTherm # Copy dataset

AmphiTherm_map <- AmphiTherm_map %>%
  mutate(metric = case_when(
    metric %in% c("CTmin", "LT50_cold") ~ "LTL",
    metric %in% c("CTmax", "LT50_hot") ~ "UTL",
    metric == "Tpref" ~ "PBT",
    TRUE ~ metric
  ))

# Plot the map
map <- ggplot() + 
 geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = -23.43663, ymax = 23.43663), 
              fill = "lightgray", 
              alpha = 0.3) + 
  geom_hline(yintercept = 0, colour = "gray", linetype = "dashed", size = 0.5) +
  geom_hline(yintercept = 23.43663, colour = "gray", linetype = "dashed", size = 0.5) +
  geom_hline(yintercept = -23.43663, colour = "gray", linetype = "dashed", size = 0.5) + 
  geom_sf(data = world, fill = "gray75", col = NA) + 
  coord_sf(xlim = c(-180, 180), ylim = c(-55.00099, 80)) + # Set the coordinate limits
       geom_point(data=AmphiTherm_map,  # Display location of species for which we have coordinates
                  aes(x = longitude, 
                      y = latitude, 
                      fill=metric,
                      shape=order), 
                  alpha = 0.7, 
                  size=4, 
                  stroke=1, 
                  col = "black") +
       scale_fill_manual(values=c("#2a9d8f", "#ffb703", "#e63946"), # Point colour for metric
                         name="none", 
                         guide = guide_legend(override.aes = list(shape = 21), 
                                         title.position = "top", 
                                         direction = "horizontal"))  + 
       scale_shape_manual(values=c(21,23),  # Set the shape of the points according to Order
                          name="Order", 
                          guide=guide_legend(title.position="top", 
                                             direction="horizontal")) + 
       labs(x = "Longitude", 
            y = "Latitude") +
       theme_minimal()+
       theme(plot.background = element_rect(fill = "white", colour = NA),
             legend.position = c(0.1, 0.13), 
             legend.justification = c(0.1, 0.5), 
             legend.background = element_blank(), 
             text = element_text(color = "black"), 
             legend.text = element_text(size = 14),
             legend.title = element_blank(), 
             axis.title = element_text(size = 25, margin = margin(t = 10, r = 0, b = 0,
        l = 0)),
             axis.text = element_text(size = 20),
             panel.border = element_rect(fill = NA,
             size = 2)) + 
       annotation_north_arrow(style = north_arrow_nautical(text_size=15, # Add nautical arrow
                                                           fill=c("grey20", "white")), 
                              height=unit(3, "cm"), 
                              width=unit(3, "cm"))

# Plot the density distribution of observations
density <- ggplot() + 
    geom_rect(aes(ymin = -Inf, ymax = Inf, xmin = -23.43663, xmax = 23.43663), 
              fill = "lightgray", 
              alpha = 0.3) + 
  geom_vline(xintercept = 0, colour = "gray", linetype = "dashed", size = 0.5) +
  geom_vline(xintercept = 23.43663, colour = "gray", linetype = "dashed", size = 0.5) +
  geom_vline(xintercept = -23.43663, colour = "gray", linetype = "dashed", size = 0.5) +
  geom_histogram(data = filter(AmphiTherm_map, metric == "UTL"), aes(x = latitude), fill = "#e63946", alpha = 0.75, bins = 50, col = "black") +
  geom_histogram(data = filter(AmphiTherm_map, metric == "PBT"), aes(x = latitude), fill = "#ffb703", alpha = 1, bins = 50, col="black") +
  geom_histogram(data = filter(AmphiTherm_map, metric == "LTL"), aes(x = latitude), fill = "#2a9d8f", alpha = 0.8, bins = 50, col = "black") +
  ylab("Number of estimates") + 
  coord_flip(xlim = c(-55.00099, 80)) + 
  theme_classic() +
    theme(axis.title.x = element_text(size = 25, margin = margin(t = 10, r = 0, b = 0,
        l = 0)), 
        axis.text.x = element_text(size = 20, colour = "black"), 
        axis.text.y = element_text(size = 20,
        colour = "black"), 
        axis.title.y = element_blank(), 
        aspect.ratio = 1, 
        plot.background = element_rect(fill = "transparent",
        colour = NA), panel.background = element_rect(fill = "transparent", colour = NA),
        panel.border = element_rect(fill = NA, size = 2))

# Combine plots
map_and_density <- (map + density + plot_layout(ncol = 2))

ggsave(map_and_density, file = "fig/Figure_2ab.png", height=12, width=20, dpi=1000, bg="transparent")

#########

# Remove observations from species not described at the species level (.sp) and extinct species
AmphiTherm_iucn <- filter(AmphiTherm_map, !is.na(IUCN_status) & IUCN_status != "EX") %>% 
          distinct(species, .keep_all = TRUE) 
AmphiTherm_iucn$IUCN_status <- factor(AmphiTherm_iucn$IUCN_status, levels = c("CR", "EN", "VU", "NT", "LC", "DD"))

# Plot the IUCN status threat distribution
IUCN_status <- 
ggplot(AmphiTherm_iucn) +
  geom_bar(aes(x=1, fill=IUCN_status), width = 0.1)+ 
  coord_flip() + 
    theme_classic() +
    ylab("Number of species") +
    theme(axis.title.x = element_text(size = 30), 
        axis.text.x = element_text(size = 25, colour = "black"), 
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(), 
        axis.line.y = element_blank(),
        plot.background = element_rect(fill = "transparent",
        colour = NA), panel.background = element_rect(fill = "transparent", colour = NA),
        panel.border = element_rect(fill = NA, size = 2)) + 
  scale_fill_manual(values = c("#c1121f", "#e36414", "#ffc300", "#936639", "#52b788", "gray75"),
                    guide = "none")

ggsave(IUCN_status, file = "fig/Figure_2c.png", height=1.5, width=20, dpi=1000, bg="transparent")
```


Note that each figure underwent cosmetic changes in Microsoft PowerPoint / Adobe Illustrator

# **Figure 3**

```{r}
# Process data
AmphiTherm_tree <- dplyr::select(Amphitherm, order, family,species, metric, life_stage_tested, mean_trait) # Only select relevant variables
AmphiTherm_tree$species <- gsub(" ", "_", AmphiTherm_tree$species) # Add underscore between species names

AmphiTherm_tree<-AmphiTherm_tree[AmphiTherm_tree$species %in% tree$tip.label, ] # Remove all species not matching the tree

pruned_tree<-drop.tip(tree, tree$tip.label[-match(AmphiTherm_tree$species, tree$tip.label)]) # Pruned tree that only contains species in the data 

AmphiTherm_tree<-mutate(AmphiTherm_tree, tip_label=species) # create a column "tip.label" to match the data to the tree

AmphiTherm_tree <- AmphiTherm_tree %>% 
  mutate(metric = ifelse(metric %in% c("CTmin", "LT50_cold"), "LTL",
                  ifelse(metric %in% c("CTmax", "LT50_hot"), "UTL",
                  ifelse(metric == "Tpref", "PBT", metric))))

AmphiTherm_tree_summary <- AmphiTherm_tree %>%
  group_by(tip_label, metric) %>%  # Group by species and metric
  summarise(
    mean_trait = mean(mean_trait, na.rm = TRUE),  # Calculate mean for each metric
    .groups = "drop"  # Drop the current grouping
  ) %>%
  pivot_wider(
    names_from = metric, 
    values_from = mean_trait,
    names_prefix = "mean_"
  ) %>%
  left_join(
    AmphiTherm_tree %>%
      group_by(tip_label) %>%
      summarise(
        n_es = n(),  # Total number of effect sizes across all metrics
        .groups = "drop"
      ),
    by = "tip_label"
  ) %>%
  mutate(
    log_n_es = log2(n_es + 1)  # Log + 1 for the plot
  )

AmphiTherm_tree_taxonomy <- dplyr::select(AmphiTherm_tree, tip_label, order, family) # Only select relevant variables
AmphiTherm_tree_taxonomy <- distinct(AmphiTherm_tree_taxonomy) # Remove duplicate species 
AmphiTherm_tree_summary <- left_join(AmphiTherm_tree_summary, AmphiTherm_tree_taxonomy, by="tip_label") # Join the data to the calculated stats for each species

# Classify life stages into 'adults', 'juveniles', or 'mix'
AmphiTherm_tree <- AmphiTherm_tree %>%
  group_by(tip_label) %>%
  mutate(life_stage_aggregated = case_when(
    life_stage_tested %in% c("larvae", "juveniles", "metamorphs") ~ "juveniles",
    life_stage_tested == "adults" ~ "adults",
    TRUE ~ as.character(life_stage_tested)
  )) %>%
  summarise(
    life_stage_final = ifelse(any(life_stage_aggregated == "adults") & any(life_stage_aggregated == "juveniles"), "mix",
                              ifelse(any(life_stage_aggregated == "juveniles"), "juveniles", "adults")),
    .groups = 'drop'
  )

# Join this back to the main summary data
AmphiTherm_tree_summary <- left_join(AmphiTherm_tree_summary, AmphiTherm_tree, by = "tip_label")

# Plot the annotated phylogenetic tree
p <- ggtree(pruned_tree, 
                layout = "fan", # Circular phylogenetic tree
                lwd = 0.5, 
                aes(colour=order))+
         scale_colour_manual(name = "Order", 
                             values=c("#60935D", "#DD9F18"))

p <- p %<+% AmphiTherm_tree_summary # Match data to the tree

p2 <- p + geom_fruit(geom = geom_tile, # Heat map
                                 mapping = aes(fill = mean_LTL), 
                                 width=35, 
                                 offset=0.1) + 
                      scale_fill_viridis(option="mako", # Colour gradient of the heat map
                                         begin=0.001, 
                                         end=0.95, 
                                         name="Cold tolerance",
                                         na.value = "grey95") 

p3 <- p2 + new_scale_fill() + geom_fruit(geom = geom_tile, # Heat map
                                 mapping = aes(fill = mean_PBT), 
                                 width=35, 
                                 offset=0.15) + 
                      scale_fill_viridis(option="cividis", # Colour gradient of the heat map
                                         begin=0.3, 
                                         end=0.95, 
                                         name="Preferred temperature",
                                         na.value = "grey95")

p4 <- p3 + new_scale_fill() + geom_fruit(geom = geom_tile, # Heat map
                                 mapping = aes(fill = mean_UTL), 
                                 width=35, 
                                 offset=0.15) + 
                      scale_fill_viridis(option="plasma", # Colour gradient of the heat map
                                         begin=0.001, 
                                         end=0.95, 
                                         name="Heat tolerance",
                                         na.value = "grey95") 

  
p5 <- p4 + new_scale_fill() + geom_fruit(geom = geom_bar, # Bar plot
                                         mapping = aes(x = log_n_es, fill = life_stage_final),
                                         col = "black",
                                         linewidth = 0.1,
                                         stat = "identity", 
                                         orientation = "y", 
                                         axis.params = list(axis = "x", # Barplot parameters
                                                            text.angle = 0, 
                                                            hjust = 0, 
                                                            text.size = 2.5,
                                                            col="transparent"),
                                         grid.params = list(alpha = 0.55),
                                         offset = 0.1, 
                                         pwidth = 0.25, 
                                         alpha = 1) + 
                                   scale_fill_manual(name = "Life stage", values = c("adults" = "gray50", "juveniles" = "gray95", "mix" = "#000814"))+ # Barplot colours
                                   scale_x_continuous(breaks = c(0, 2, 4, 6, 8, 10),  # Log scale values
                                                      labels = c(0, 3, 15, 63, 255, 1023)) +  # Original values
                                   theme(legend.position="bottom", 
                                         legend.direction ="horizontal")+
                                   guides() # Remove duplicated legend

p5

ggsave(p5, file = "fig/Figure_3.png", height = 20, width =20, dpi = 1100, bg="transparent")
```

# **Figure 4**

```{r}
# Process data
AmphiTherm_taxonomy<-read_csv("data/Metadata_Jetz_Pyron_2018.csv") # Load amphibian classification from Jetz and Pyron (2018)
AmphiTherm_taxonomy$tip.label<-AmphiTherm_taxonomy$`Scientific Name` # Rename variable to match our dataset
AmphiTherm_taxonomy$order<-AmphiTherm_taxonomy$Taxon # Rename variable to match our dataset
AmphiTherm_taxonomy$tip.label <- gsub(" ", "_", AmphiTherm_taxonomy$tip.label) # Add underscore between species names

AmphiTherm_tree_all<-dplyr::select(AmphiTherm, order, family, species, metric) # Only select relevant variables
AmphiTherm_tree_all$species <- gsub(" ", "_", AmphiTherm_tree_all$species) # Add underscore between species names


AmphiTherm_tree_all<-mutate(AmphiTherm_tree_all, tip.label= species) # create a column "tip.label" to match the data to the tree

# Assign LT50 metrics to UTL or LTL
AmphiTherm_tree_all <- AmphiTherm_tree_all %>%
  mutate(metric = case_when(
    metric %in% c("CTmin", "LT50_cold") ~ "LTL",
    metric %in% c("CTmax", "LT50_hot") ~ "UTL",
    metric == "Tpref" ~ "PBT",
    TRUE ~ metric
  ))

AmphiTherm_tree_summary <- AmphiTherm_tree_all %>%
  mutate(UTL = ifelse(metric == "UTL", "UTL", NA),
         PBT = ifelse(metric == "PBT", "PBT", NA),
         LTL = ifelse(metric == "LTL", "LTL", NA)) %>%
  group_by(tip.label) %>%
  summarise(
    UTL = ifelse(any(!is.na(UTL)), "UTL", NA),
    PBT = ifelse(any(!is.na(PBT)), "PBT", NA),
    LTL = ifelse(any(!is.na(LTL)), "LTL", NA)
  )

AmphiTherm_tree_taxo_all<-dplyr::select(AmphiTherm_tree_all, tip.label, order, family) # Only select relevant variables
AmphiTherm_tree_taxo_all<-distinct(AmphiTherm_tree_taxo_all) # Remove duplicate species 
AmphiTherm_tree_summary<-left_join(AmphiTherm_tree_summary, AmphiTherm_tree_taxo_all, by="tip.label") # Join the data to the calculated stats for each species

species_in_tree<- data.frame(tip.label=tree$tip.label)# Get all species names from Jetz and Pyron (2018)
AmphiTherm_tree_summary<-full_join(AmphiTherm_tree_summary, species_in_tree)
AmphiTherm_tree_summary<- full_join(AmphiTherm_tree_summary, AmphiTherm_taxonomy, by="tip.label")
AmphiTherm_tree_summary <- mutate(AmphiTherm_tree_summary, Order = coalesce(order.x, order.y)) # Combine content columns
AmphiTherm_tree_summary<-filter(AmphiTherm_tree_summary, Order!="Outgroup") # Remove humans

# Plot the annotated phylogenetic tree
p_all<-ggtree(tree, 
                layout = "fan", # Circular phylogenetic tree
                lwd = 0.2,
                aes(colour=Order))+
       scale_colour_manual(values=c("#60935D", "#DD9F18", "#925D83"),
                           na.value="black")

p_all <- p_all %<+% AmphiTherm_tree_summary # Match data to the tree

p2_all <- p_all + new_scale_fill() + geom_fruit(geom = geom_tile, # Heat map
                             mapping = aes(fill = LTL), 
                                           width=25, 
                                           offset=0.06) + 
                  scale_fill_manual(values = "#2a9d8f",
                                    na.value = "gray95") +
                  theme(legend.position="bottom", 
                        legend.direction ="horizontal")

p3_all <- p2_all + new_scale_fill() + geom_fruit(geom = geom_tile, # Heat map
                             mapping = aes(fill = PBT), 
                                           width=25, 
                                           offset=0.075) + 
                  scale_fill_manual(values = "#ffb703",
                                    na.value = "gray95") +
                  theme(legend.position="bottom", 
                        legend.direction ="horizontal")

p4_all <- p3_all + new_scale_fill() + geom_fruit(geom = geom_tile, # Heat map
                             mapping = aes(fill = UTL), 
                                           width=25, 
                                           offset=0.075) + 
                  scale_fill_manual(values = "#e63946",
                                    na.value = "gray95") +
                  theme(legend.position="bottom", 
                        legend.direction ="horizontal")

p4_all

ggsave(p4_all, file = "fig/Figure_4.png", height=20, width=20, dpi=1100, bg = "transparent")
```



